apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
  namespace: kube-system
  labels:
    claimName: prometheus-pv
spec:
  capacity:
    storage: 150Gi
  accessModes:
    - ReadWriteMany
  nfs:
    # FIXME: use the right IP
    server: 192.168.165.63
    path: "/data2/prometheus"
